[profile.default]
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out" },
]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

[profile.default.fuzz]
runs = 100
seed = "0x4444"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.ci.fuzz]
runs = 1000

[profile.ci]
fuzz_runs = 100000
solc = "./bin/solc-static-linux"

remappings = [
    "layerzero/=lib/layerzero/contracts/",
    "openzeppelin/=lib/openzeppelin/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
